CREATE TABLE <SPAM TABLE NAME> (
 date INT,
 ipaddr STRING,
 fqdn STRING,
 ptr STRING,
 file STRING
)
PARTITIONED BY(dt STRING, sv STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ' '
LINES TERMINATED BY '\n';
